mvcCalisma/mvcCalisma/Controllers/Home2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcCalisma.Controllers
{
    public class Home2Controller : Controller
    {
        // GET: Home2
        public ActionResult Index()
        {
            return View();
        }
    }
}

mvcCalisma/mvcCalisma/Controllers/Home3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcCalisma.Controllers
{
    public class Home3Controller : Controller
    {
        // GET: Home3
        public ActionResult blog1()
        {
            return View();
        }
        public ActionResult blog2()
        {
            return View();
        }
    }
}

mvcCalisma/mvcCalisma/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcCalisma.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult HomePage()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
    }
}

mvcCalisma/mvcCalisma/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>Html Helper</h2>
@Html.Label("Ad giriniz: ")
@Html.TextBox("text1")<br />
@Html.Label("Onaylıyorum: ")
@Html.CheckBox("check1", false) <br />
@Html.ActionLink("Home other", "Index", "Home2")<br />

mvcCalisma/mvcCalisma/Views/Home/HomePage.cshtml
@{
    ViewBag.Title = "HomePage";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>HomePage</h2>
@Html.ActionLink("Home other", "Index", "Home2")<br />
@Html.ActionLink("Home other 2","blog1","Home3")<br />

mvcCalisma/mvcCalisma/Views/Home2/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>Index</h2>

mvcCalisma/mvcCalisma/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Views/Shared/main.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        #menu ul li {
            display: inline-block;
            width: 100px;
            height: 30px;
            text-align: center;
            border: 1px solid #000a44;
            background-color: #0026ff;
            line-height: 30px;
            vertical-align: middle;
        }

        #menu a {
            color: #fff;
            text-decoration: none;
            font-size: smaller;
        }

        #menu li:hover {
            background-color: aqua;
        }

        #menu a:hover {
            background-color: #000a44;
        }
    </style>
</head>
<body>
    <div style="padding:30px;">
        <div id="menu">
            @*header*@
            <ul>
                <li> @Html.ActionLink("Home Page", "HomePage", "Home")</li>
                <li> @Html.ActionLink("About", "About", "Home")</li>
                <li> @Html.ActionLink("Contaxt", "Index", "Home2")</li>
            </ul>
        </div>
        <hr />
        <div>
            @RenderBody()
        </div>
        <hr />
        <div>
            @*footer*@
            <b>Tüm Hakları Saklıdır. &copy;</b>
        </div>
        <hr />
    </div>
</body>
</html>

mvcCalisma/mvcCalisma/Views/Shared/_LayoutPage2.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<div class="container-fluid col-md-12">
    <div class="container col-md-8" >
        @RenderBody()
    </div>
    <div class="container col-md-4 " >
        <b>İletisim Numaralarımız</b>
        <ul>
            <li>245 78 79 44</li>
            <li>245 78 79 44</li>
            <li>245 78 79 44</li>
            <li>245 78 79 44</li>
        </ul>
    </div>
</div>

mvcCalisma/mvcCalisma/Views/Shared/_LayoutPage3.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        .block {
            margin: 10px;
            display: block;
            border: 2px dotted gray;
            padding: 10px;
        }

        .block2 {
            margin: 5px;
            display: inline-block;
            border: 2px dotted aqua;
            padding: 10px;
        }

        #menu ul li {
            display: inline-block;
            width: 100px;
            height: 30px;
            text-align: center;
            border: 1px solid #000a44;
            background-color: #0026ff;
            line-height: 30px;
            vertical-align: middle;
        }

        #menu a {
            color: #fff;
            text-decoration: none;
            font-size: smaller;
        }

        #menu li:hover {
            background-color: aqua;
        }

        #menu a:hover {
            background-color: #000a44;
        }
    </style>
</head>
<body>
    <div id="menu" class="block">
        @*header*@
        <ul>
            <li> @Html.ActionLink("Home Page", "HomePage", "Home")</li>
            @RenderSection("link")
        </ul>
    </div>
    <div class="block">
        @RenderBody()
        
    </div>
    <div class="block">
        @*footer*@
        @RenderSection("footer")
        <b>Tüm Hakları Saklıdır. &copy;</b>
    </div>
</body>
</html>